name: Build Shibboleth Nginx Module for Debian Bookworm

on:
  push:
    branches:
      - main
    paths:
      - scripts/debian/bookworm/*
      - .github/workflows/debian-bookworm-build.yml
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      force_rebuild_shibboleth_modules:
        description: 'Force rebuild Nginx Shibboleth modules'
        required: false
        default: false
        type: boolean

jobs:
  debian-bookworm-docker-build:
    name: Build packages for Debian Bookworm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          lfs: true
          sparse-checkout: |
            repo/debian/bookworm
            scripts/debian/bookworm
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Build Shibboleth Nginx modules for Debian Bookworm
        run: >
          docker run --rm
          -v ${{ github.workspace }}/repo/debian/bookworm:/repo
          -v ${{ github.workspace }}/scripts/debian/bookworm:/scripts:ro
          -e FORCE_REBUILD_SHIBBOLETH_MODULES=$FORCE_REBUILD_SHIBBOLETH_MODULES
          debian:bookworm
          /bin/bash /scripts/cron-build-shib-nginx-mod.sh
        env:
          FORCE_REBUILD_SHIBBOLETH_MODULES: ${{ inputs.force_rebuild_shibboleth_modules }}

      - name: Commit build package
        run: |
          git config --global user.name 'GitHub build bot'
          git config --global user.email 'buildbot@users.noreply.github.com'
          (git add repo/debian/bookworm/pool/non-free/*.deb && git commit -m "[automated] Debian Bookworm package added" && git push) || echo "No new packages found, skip updating."
