name: Udpate Debian Bookworm repo

on:
  push:
    branches:
      - main
    paths:
      - repo/debian/bookworm/pool/non-free/*.deb
      - .github/workflows/debian-bookworm-update-repo.yml
  workflow_dispatch:
    inputs:
      force_recreate_repo:
        description: 'Force recreate Debian repository'
        required: false
        type: boolean
        default: false

jobs:
  rhel8-update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          lfs: true
          sparse-checkout: |
            repo/debian/bookworm
            scripts/debian/bookworm
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Update Debian Bookworm repository
        run: >
          docker run --rm
          -v ${{ github.workspace }}/repo/debian/bookworm:/repo
          -v ${{ github.workspace }}/scripts/debian/bookworm:/scripts:ro
          -e FORCE_RECREATE_REPO=$FORCE_RECREATE_REPO
          -e GPG_SIGNING_KEY=$GPG_SIGNING_KEY
          debian:12
          /bin/bash /scripts/update-repo.sh
        env:
          FORCE_RECREATE_REPO: ${{ inputs.force_recreate_repo }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Commit Debian Bookworm repo
        run: |
          git config --global user.name 'GitHub build bot'
          git config --global user.email 'buildbot@users.noreply.github.com'
          (git add repo/debian/bookworm/dists/bookworm/Release* && git add repo/debian/bookworm/dists/bookworm/InRelease && git add repo/debian/bookworm/dists/bookworm/non-free/Packages* && git commit -m "[automated] Debian Bookworm repo updated" && git push) || echo "No new packages found, skip updating."
